# All services can share this build pipeline yaml file as long as the directories have the expected structure and files.
# For more information refer to the Ev2_README.md file
#################################################################################
# Variables that should be defined in pipeline settings.
# directoryName: The name of the directory where the service/shared-resources code is located.
# isService: true if the pipeline is for a service, false if it is for shared-resources.
# rolloutInfra: Prod or Test based on which configuration file needs to be used.
# forceReinstallCredentialProvider: true (to avoid credential provider caching issues)
#################################################################################
#                               OneBranch Pipelines                             #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

trigger: none

#Variable structure was changed from the default version of OneBranch template yaml file. It is now
# - name:
#   value:
# instead of
# - name: value
# to be able tosupport variable groups.
variables:
  - group: ADO_PAT
  - name: CDP_DEFINITION_BUILD_COUNT
    value: $[counter('', 0)] # needed for onebranch.pipeline.version task https://aka.ms/obpipelines/versioning
  - name: LinuxContainerImage
    value: "mcr.microsoft.com/onebranch/cbl-mariner/build:2.0" # Docker image which is used to build the project https://aka.ms/obpipelines/containers
  - name: DEBIAN_FRONTEND
    value: noninteractive
  - name: DisableGoCliScan
    value: true

resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@templates # https://aka.ms/obpipelines/templates
  parameters:
    globalSdl: # https://aka.ms/obpipelines/sdl
      # tsa:
      #   enabled: true # SDL results of non-official builds aren't uploaded to TSA by default.
      # credscan:
      #   suppressionsFile: $(Build.SourcesDirectory)\.config\CredScanSuppressions.json
      policheck:
        break: true # always break the build on policheck issues. You can disable it by setting to 'false'
      # suppression:
      #   suppressionFile: $(Build.SourcesDirectory)\.gdn\global.gdnsuppress

    stages:
      - stage: createArtifactsFiles
        jobs:
          - job: buildServiceImage
            condition: eq(variables['isService'], 'true')
            pool:
              type: docker
              os: Linux
            variables:
              ob_git_checkout: true
            steps:
              - task: onebranch.pipeline.imagebuildinfo@1
                displayName: Build docker $(directoryName) image
                inputs:
                  arguments: " --build-arg PAT=$(READPAT)"
                  repositoryName: $(directoryName)
                  dockerFileRelPath: $(directoryName)/server/Dockerfile
                  dockerFileContextPath: $(directoryName)/server
                  enable_network: true
                  enable_isolated_acr_push: false # Isolated ACRs are only in AME tenant, not corp. So, not enabling.
                  build_tag: $(Build.BuildNumber)-$(Build.SourceVersion)
                  saveImageToPath: $(directoryName)-image.tar
      - stage: combineArtifacts
        dependsOn: createArtifactsFiles
        jobs:
          - job: prepare
            pool:
              type: linux
            variables: # More settings at https://aka.ms/obpipelines/yaml/jobs
              ob_outputDirectory: "$(Build.SourcesDirectory)/Ev2Artifacts" # this directory is uploaded to pipeline artifacts, reddog and cloudvault. More info at https://aka.ms/obpipelines/artifacts
            steps: # These steps will be run in unrestricted container's network
              - task: DownloadPipelineArtifact@2
                # This task downloads the published docker image artifact created in the previous stage, only if we are building a service.
                condition: eq(variables['isService'], 'true')
                displayName: "Download Image Artifacts"
                inputs:
                  targetPath: $(directoryName)/server/Ev2/Ev2Specs/Build
                  artifact: drop_createArtifactsFiles_buildServiceImage
              - task: AzureCLI@2
                displayName: "Prepare Artifacts"
                inputs:
                  # azureSubscription corresponds to the name of the azure resource manager service
                  # connection that is supposed to be used for the pipeline task.
                  azureSubscription: ServiceHubServiceConnection
                  scriptType: "bash"
                  scriptLocation: scriptPath
                  scriptPath: "pipeline-files/buildEv2Artifacts.sh"
                  arguments: "$(directoryName) $(ob_outputDirectory) $(isService) $(rolloutInfra) $(Build.BuildNumber) false"
                env:
                  READPAT: $(READPAT)
