/*
 * api.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package restsdk

import (
	"time"
)

type StartLongRunningOperationRequest struct {
	EntityId            string    `json:"entityId,omitempty"`
	EntityType          string    `json:"entityType,omitempty"`
	ExpirationTimestamp time.Time `json:"expirationTimestamp,omitempty"`
}
