/*
 * api.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package restsdk

type CreateResourceGroupRequest struct {
	Name   string `json:"name,omitempty"`
	Region string `json:"region,omitempty"`
}
