/*
 * api.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package restsdk

type ReadStorageAccountResponse struct {
	StorageAccount *StorageAccount `json:"storageAccount,omitempty"`
}
