apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ include "server.fullname" . }}
  namespace: {{ include "server.fullname" . }}
spec:
  mtls:
    # Additional modes: https://istio.io/latest/docs/concepts/security/#mutual-tls-authentication
    mode: STRICT
