apiVersion: deployer.aks/v1
kind: AksApp
metadata:
  name: <<.serviceInput.directoryName>>-client
  namespace: <<.serviceInput.directoryName>>
spec:
  variables:
    DEPLOY_ENV: e2e
    ACR_SERVER: aksdeploymente2eeastus.azurecr.io
    ACR_MSI_ResourceID: /subscriptions/4be8920b-2978-43d7-ab14-04d8549c1d05/resourceGroups/AKSE2EInfra/providers/Microsoft.ManagedIdentity/userAssignedIdentities/akse2eaks-svc-acr-pull
    CLOUD_ENVIRONMENT: AZUREPUBLICCLOUD
    REPLICAS: "1"
    API_LINKERD: "enabled"
    E2E_OVERLAY_RESOURCE_SUBSCRIPTION: "${E2E_OVERLAY_RESOURCE_SUBSCRIPTION}"
    ENABLE_GOSHUTTLE_LOG: "ALL"
    RG_NAME: "<<.serviceInput.directoryName>>-resource-group"
    RG_REGION: "eastus"
    CALL_ALL_RG_OPS: "true"
