apiVersion: v1
kind: Namespace
metadata:
  labels:
    # Required for AKS Managed Istio: https://learn.microsoft.com/en-us/azure/aks/istio-deploy-addon#enable-sidecar-injection
    istio.io/rev: asm-1-19
  name: {{ include "server.fullname" . }}
