apiVersion: v1
kind: Service
metadata:
  name: <<.serviceInput.directoryName>>-server
  labels:
    app: <<.serviceInput.directoryName>>-server
  namespace: (V_NAMESPACE)
spec:
  selector:
    app: <<.serviceInput.directoryName>>-server
  ports:
    - port: 50051
      protocol: TCP
      targetPort: 50051
