###################################
# User inputs.
###################################
serviceInput:
  # The directory name after destination_dir_prefix. It holds the service.
  directoryName: mygreeterv3
  # The service name in the protobuf.
  serviceName: MyGreeter
  # Whether to add this service to the umbrella pipeline
  runPipeline: true
  # The primary email address for the service. This is for Ev2 notifications.
  # To include multiple email addresses, separate them with a comma.
  contactEmail: ksehgal@microsoft.com
  ################################
  # The template name to use for this service.
  # Only used by internal templating code to determine which template to use.
  templateName: mygreeterGoTemplate
