#Where the templates for the service are stored
mygreeterGoTemplate: ../templates/service_templates
#Where the templates for the resources are stored
resourcesTemplate: ../templates/resource-provisioning_templates
#Where the templates for the pipelines are stored
pipelineTemplate: ../templates/pipeline_templates
#Where the templates for the pipelines are stored
readmeTemplate: ../templates/readme_templates
