openapi: 3.0.1
info:
  title: api.proto
  version: version not set
servers:
- url: /
tags:
- name: BasicService
paths:
  /v1/hello:
    post:
      tags:
      - BasicService
      summary: Send a greeting
      description: This operation sends a greeting to the user.
      operationId: BasicService_SayHello
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HelloRequest'
        required: true
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloReply'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      x-codegen-request-body-name: body
components:
  schemas:
    Address:
      type: object
      properties:
        city:
          title: The city name
          type: string
        state:
          title: The state name
          type: string
        zipcode:
          title: The zip code
          type: integer
          format: int32
        street:
          title: The street name
          type: string
    HelloReply:
      type: object
      properties:
        message:
          type: string
      example:
        message: message
    HelloRequest:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
          format: int32
        email:
          type: string
        address:
          $ref: '#/components/schemas/Address'
    protobufAny:
      type: object
      properties:
        '@type':
          type: string
      additionalProperties:
        type: object
      x-schema-name: protobufAny
    rpcStatus:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/protobufAny'
x-original-swagger-version: "2.0"
