apiVersion: deployer.aks/v1
kind: AksApp
metadata:
  name: <<.serviceInput.directoryName>>-server
  namespace: <<.sharedInput.productShortName>>-<<.serviceInput.directoryName>>
spec:
  variables:
    DEPLOY_ENV: e2e
    ACR_SERVER: aksdeploymente2eeastus.azurecr.io
    ACR_MSI_ResourceID: /subscriptions/4be8920b-2978-43d7-ab14-04d8549c1d05/resourceGroups/AKSE2EInfra/providers/Microsoft.ManagedIdentity/userAssignedIdentities/akse2eaks-svc-acr-pull
    CLOUD_ENVIRONMENT: AZUREPUBLICCLOUD
    REPLICAS: "1"
    API_LINKERD: "enabled"
    E2E_OVERLAY_RESOURCE_SUBSCRIPTION: "${E2E_OVERLAY_RESOURCE_SUBSCRIPTION}"
    ENABLE_GOSHUTTLE_LOG: "ALL"
    SUBSCRIPTION_ID: "8ecadfc9-d1a3-4ea4-b844-0d9f87e4d7c8"
    # In the E2E environment, there is a single Managed Service Identity (MSI) that we utilize. This MSI exists in the AKSE2EInfra resource group and is named 'akse2eservicehub'.
    IDENTITY_RESOURCE_ID: "/subscriptions/4be8920b-2978-43d7-ab14-04d8549c1d05/resourceGroups/AKSE2EInfra/providers/Microsoft.ManagedIdentity/userAssignedIdentities/akse2eservicehub"
